# Run order install -> before_script -> script

services:
  - postgresql
language: python
python:
  - "3.6"
install:
  - cd backend
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE sustainable_city_ci;"
script:
  - python manage.py migrate
  - python manage.py test dashboard
