# Run order install -> before_script -> script

matrix:
  include:
    - services:
        - postgresql
        - memcached
      language: python
      python:
        - "3.6"
      install:
        - cd backend
        - pip install -r requirements.txt
      before_script:
        - psql -c "CREATE DATABASE sustainable_city_ci;"
      script:
        - pylint --load-plugins pylint_django ./dashboard
        - pylint --load-plugins pylint_django ./api
        - pylint --load-plugins pylint_django ./reports
        - python manage.py migrate
        - coverage run --source='.' manage.py test dashboard api reports
        - coverage report

    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - node_modules
      script:
        - cd frontend
        - npm install
        - npm test
        # - npm run build
